dist: xenial

language: python

matrix:
  include:
    - python: "2.7"
      env:
        - TOX_ENV=py2.7
    - python: "2.7"
      env:
        - TOX_ENV=lint
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
      dist: bionic

before_install:
  - sudo apt-get install -y net-tools

install:
  - pip install -U pip codecov tox tox-travis

script:
  - tox

after_success:
  - codecov
