dist: xenial

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get install -y net-tools

install:
  - pip install -U pip codecov tox tox-travis

script:
  - tox

after_success:
  - codecov
